# Generated by Django 5.0.3 on 2024-03-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alzayedrentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headiline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='homepage')),
            ],
        ),
        migrations.DeleteModel(
            name='home_slides',
        ),
    ]
