# Generated by Django 5.0.3 on 2024-03-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alzayedrentals', '0002_home_slide_delete_home_slides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_slide',
            name='description',
        ),
        migrations.RemoveField(
            model_name='home_slide',
            name='headiline',
        ),
    ]
