# Generated by Django 5.0.3 on 2024-03-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alzayedrentals', '0003_remove_home_slide_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_slide1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headiline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='homepage')),
            ],
        ),
        migrations.CreateModel(
            name='home_slide2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headiline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='homepage')),
            ],
        ),
        migrations.CreateModel(
            name='home_slide3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headiline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='homepage')),
            ],
        ),
        migrations.DeleteModel(
            name='home_slide',
        ),
    ]
