# Generated by Django 5.0.3 on 2024-03-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alzayedrentals', '0005_alter_home_slide1_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equipments')),
                ('type', models.CharField(choices=[('EXCAVATOR', 'EXCAVATOR'), ('CRANES', 'CRANES'), ('CLEANING EQUIPMENT', 'CLEANING EQUIPMENT'), ('LIFTING EQUIPMENT', 'LIFTING EQUIPMENT'), ('TRUCK', 'TRUCK'), ('TANKER', 'TANKER'), ('POWER TOOLS', 'POWER TOOLS'), ('PUMP', 'PUMP'), ('CONSTRUCTION EQUIPMENTS', 'CONSTRUCTION EQUIPMENTS')], default='EXCAVATOR', max_length=50)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alzayedrentals.category')),
            ],
        ),
    ]
