# Generated by Django 5.0.3 on 2024-03-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alzayedrentals', '0007_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='homepage')),
                ('image2', models.ImageField(upload_to='homepage')),
                ('image3', models.ImageField(upload_to='homepage')),
            ],
        ),
        migrations.DeleteModel(
            name='home_slide1',
        ),
        migrations.DeleteModel(
            name='home_slide2',
        ),
        migrations.DeleteModel(
            name='home_slide3',
        ),
    ]
